const EspecialidadesModel = require('../models/especialidadesModel');

const EspecialidadesController = {
  async getAll(req, res) {
    try {
      const especialidades = await EspecialidadesModel.getAll();
      res.status(200).json(especialidades);
    } catch (error) {
      console.error('Error al obtener las especialidades:', error);
      res.status(500).json({ error: 'Error al obtener las especialidades' });
    }
  },
};

module.exports = EspecialidadesController;






// instrucciones
// traer los datos del planteles_cursos por el id del plantel
// y en la tabla de cursos_docentes traer los datos por cursoId
//
// 
// -- Generated by the database client.
// CREATE TABLE planteles_cursos(
//   id SERIAL NOT NULL,
//   plantel_id integer,
//   curso_id integer,
//   horario text,
//   cupo_maximo integer,
//   requisitos_extra text,
//   fecha_inicio date,
//   fecha_fin date,
//   estatus boolean DEFAULT true,
//   created_at timestamp without time zone DEFAULT now(),
//   updated_at timestamp without time zone DEFAULT now(),
//   PRIMARY KEY(id),
//   CONSTRAINT fk_planteles_cursos_curso FOREIGN key(curso_id) REFERENCES cursos(id),
//   CONSTRAINT fk_planteles_cursos_plantel FOREIGN key(plantel_id) REFERENCES planteles(id),
//   CONSTRAINT planteles_cursos_curso_id_fkey FOREIGN key(curso_id) REFERENCES cursos(id),
//   CONSTRAINT planteles_cursos_plantel_id_fkey FOREIGN key(plantel_id) REFERENCES planteles(id),
//   CONSTRAINT planteles_cursos_cupo_maximo_check CHECK ((cupo_maximo > 0))
// );
// -- Generated by the database client.
// CREATE TABLE cursos_docentes(
//   id SERIAL NOT NULL,
//   curso_id integer,
//   docente_id integer,
//   fecha_asignacion date DEFAULT now(),
//   estatus boolean DEFAULT true,
//   created_at timestamp without time zone DEFAULT now(),
//   updated_at timestamp without time zone DEFAULT now(),
//   PRIMARY KEY(id),
//   CONSTRAINT cursos_docentes_curso_id_fkey FOREIGN key(curso_id) REFERENCES cursos(id),
//   CONSTRAINT cursos_docentes_docente_id_fkey FOREIGN key(docente_id) REFERENCES docentes(id),
//   CONSTRAINT fk_cursos_docentes_curso FOREIGN key(curso_id) REFERENCES cursos(id),
//   CONSTRAINT fk_cursos_docentes_docente FOREIGN key(docente_id) REFERENCES docentes(id)
// );
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 